# Generated by Django 4.0.5 on 2022-06-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, error_messages={'blank': 'You cannot leave it blank', 'null': 'This field cannot be null'}, max_length=255, null=True, unique=True)),
                ('desc', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('is_live', models.BooleanField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
